### ISSUE TITLE
Foxy Jobs - No SSH Credentials Set

### ISSUE THREAD

**Issue by dniewinski** [ros2/ros_buildfarm_config#147]
We recently added Foxy to our buildfarm.  All ROS distros build their SRC and BIN jobs correctly, except for Foxy (our first ROS2 distro in the farm).  When jobs are updated from the reconfigure jobs, the ssh-agent credentials appear to not be set properly.  This leads to an immediate failure of the job:
`java.io.IOException: [ssh-agent] Could not find specified credentials`

If I edit the job configuration, the proper credentials are auto-filled.  Just opening and saving the job again, lets the jobs run properly.  

I'm not sure if the config is the right place for this issue, or if it's another repo.

**Comment by nuclearsandwich** [comment]
> If I edit the job configuration, the proper credentials are auto-filled. Just opening and saving the job again, lets the jobs run properly.

This usually indicates that the credential id given in the build file is not present on the Jenkins instance. By editing the job manually the credential ID field is automatically populated with the first valid one.

I would suggest comparing the credential ID in Jenkins to the `upload_credential_id` field in your foxy/release-build.yaml file.



> I'm not sure if the config is the right place for this issue, or if it's another repo.

Since the public configuration repositories are for the official build farms (build.ros.org and build.ros2.org respectively) I don't think that opening issues here is the best avenue for issues with a separate build farm. I think this best belongs as a question on https://answers.ros.org which can then be escalated to an issue if it turns out to be an error in the ros_buildfarm or buildfarm_deployment projects..

**Comment by dniewinski** [comment]
The credential ID was the issue.  All is working now.  Thanks for the help
